// Copyright ©2016 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package vgtex provides a vg.Canvas implementation for LaTeX, targeted at
// the TikZ/PGF LaTeX package: https://sourceforge.net/projects/pgf
//
// vgtex generates PGF instructions that will be interpreted and rendered by LaTeX.
// vgtex allows to put any valid LaTeX notation inside plot's strings.
package vgtex // import "gonum.org/v1/plot/vg/vgtex"

import (
	"bytes"
	"image"
	"image/color"
	"io"
	"math"

	"gonum.org/v1/plot/font"
	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/draw"
)

const degPerRadian = 180 / math.Pi

const (
	defaultHeader = `%%%%%% generated by gonum/plot %%%%%%
\documentclass{standalone}
\usepackage{pgf}
\begin{document}
`
	defaultFooter = "\\end{document}\n"
)

func init() {
	draw.RegisterFormat("tex", func(w, h vg.Length) vg.CanvasWriterTo {
		return NewDocument(w, h)
	})
}

// Canvas implements the vg.Canvas interface, translating drawing
// primitives from gonum/plot to PGF.
type Canvas struct {
	buf   *bytes.Buffer
	w, h  vg.Length
	stack []context

	// If document is true, Canvas.WriteTo will generate a standalone
	// .tex file that can be fed to, e.g., pdflatex.
	document bool
	id       int64 // id is a unique identifier for this canvas
}

type context struct {
	color      color.Color
	dashArray  []vg.Length
	dashOffset vg.Length
	linew      vg.Length
}

// New returns a new LaTeX canvas.
func New(w, h vg.Length) *Canvas { _ = "STUB: not implemented"; return nil }

// NewDocument returns a new LaTeX canvas that can be readily
// compiled into a standalone document.
func NewDocument(w, h vg.Length) *Canvas { _ = "STUB: not implemented"; return nil }

func newCanvas(w, h vg.Length, document bool) *Canvas { _ = "STUB: not implemented"; return nil }

func (c *Canvas) context() *context { _ = "STUB: not implemented"; return nil }

// Size returns the width and height of the canvas.
func (c *Canvas) Size() (w, h vg.Length) {
	_ = "STUB: not implemented"

	// SetLineWidth implements the vg.Canvas.SetLineWidth method.
	return *new(vg.Length), *new(vg.Length)
}

func (c *Canvas) SetLineWidth(w vg.Length) { _ = "STUB: not implemented"; return }

// SetLineDash implements the vg.Canvas.SetLineDash method.
func (c *Canvas) SetLineDash(pattern []vg.Length, offset vg.Length) {
	_ = "STUB: not implemented"
	return
}

// SetColor implements the vg.Canvas.SetColor method.
func (c *Canvas) SetColor(clr color.Color) { _ = "STUB: not implemented"; return }

// Rotate implements the vg.Canvas.Rotate method.
func (c *Canvas) Rotate(rad float64) { _ = "STUB: not implemented"; return }

// Translate implements the vg.Canvas.Translate method.
func (c *Canvas) Translate(pt vg.Point) { _ = "STUB: not implemented"; return }

// Scale implements the vg.Canvas.Scale method.
func (c *Canvas) Scale(x, y float64) { _ = "STUB: not implemented"; return }

// Push implements the vg.Canvas.Push method.
func (c *Canvas) Push() { _ = "STUB: not implemented"; return }

// Pop implements the vg.Canvas.Pop method.
func (c *Canvas) Pop() { _ = "STUB: not implemented"; return }

// Stroke implements the vg.Canvas.Stroke method.
func (c *Canvas) Stroke(p vg.Path) { _ = "STUB: not implemented"; return }

// Fill implements the vg.Canvas.Fill method.
func (c *Canvas) Fill(p vg.Path) { _ = "STUB: not implemented"; return }

// FillString implements the vg.Canvas.FillString method.
func (c *Canvas) FillString(f font.Face, pt vg.Point, text string) {
	_ = "STUB: not implemented"
	return
}

// DrawImage implements the vg.Canvas.DrawImage method.
// DrawImage will first save the image inside a PNG file and have the
// generated LaTeX reference that file.
// The file name will be "gonum-pgf-image-<canvas-id>-<time.Now()>.png
func (c *Canvas) DrawImage(rect vg.Rectangle, img image.Image) { _ = "STUB: not implemented"; return }

func (c *Canvas) indent(s string) string { _ = "STUB: not implemented"; return "" }

func (c *Canvas) wtex(s string, args ...any) { _ = "STUB: not implemented"; return }

func (c *Canvas) wstyle() { _ = "STUB: not implemented"; return }

func (c *Canvas) wdash() { _ = "STUB: not implemented"; return }

func (c *Canvas) wlineWidth() { _ = "STUB: not implemented"; return }

func (c *Canvas) wcolor() { _ = "STUB: not implemented"; return }

// FIXME(sbinet) \color will last until the end of the current TeX group
// use \pgfsetcolor and \pgfsetstrokecolor instead.
// it needs a named color: define it on the fly (storing it at the beginning
// of the document.)

func (c *Canvas) wpath(p vg.Path) { _ = "STUB: not implemented"; return }

// WriteTo implements the io.WriterTo interface, writing a LaTeX/pgf plot.
func (c *Canvas) WriteTo(w io.Writer) (int64, error) { _ = "STUB: not implemented"; return 0, nil }
